### USER
//register
post http://localhost:5000/users/register
Content-Type: application/json

{
  "name":"fath",
  "email":"fath@gmail.com",
  "password":"12345678",
  "profession":"web developer"

}

###
//login
post http://localhost:5000/users/login
Content-Type: application/json

{
  "email":"fath@gmail.com",
  "password":"12345678"
}

###
//update
put http://localhost:5000/users/51
Content-Type: application/json

{
  "name":"al fath",
  "email":"fath@gmail.com",
  "password":"12345678",
  "avatar":"https://imagesa.com",
  "profession":"backend web dev" 
}

###
//get user by id
get http://localhost:5000/users/5


###
//get users
get http://localhost:5000/users

###
//user logout
post http://localhost:5000/users/logout
Content-Type: application/json

{
  "user_id":"5"
}

### REFRESH TOKENS
// create refresh token 
POST  http://localhost:5000/refresh_tokens
Content-Type: application/json

{
  "refresh_token":"2137sadhjkhu214dsa",
  "user_id": 4
}

###
// get token 
get  http://localhost:5000/refresh_tokens?refresh_token=2137sadhjkhu214dsa